wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.3
    cli_version: 0.17.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1719982008
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 2
      - 23
      4: 3.12.3
      5: 0.17.3
      8:
      - 4
      - 5
      13: darwin-arm64
num_images:
  desc: null
  value: 10
num_epochs:
  desc: null
  value: 20000
learning_rate:
  desc: null
  value: 1.0e-05
model:
  desc: null
  value: Net_